/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLeftmenu: typeof import('./components/AppLeftmenu.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    MainPage: typeof import('./components/MainPage.vue')['default']
    Modal: typeof import('./components/modals/modal.vue')['default']
    ModalNewAdam: typeof import('./components/modals/modalNewAdam.vue')['default']
    Pad: typeof import('./components/Pad.vue')['default']
    PageCalls: typeof import('./components/pages/pageCalls.vue')['default']
    PageLaws: typeof import('./components/pages/pageLaws.vue')['default']
    PageMainpanel: typeof import('./components/pages/pageMainpanel.vue')['default']
    PageResidentbase: typeof import('./components/pages/pageResidentbase.vue')['default']
    PageResidentInfo: typeof import('./components/pages/pageResidentInfo.vue')['default']
    PageTenCodes: typeof import('./components/pages/pageTenCodes.vue')['default']
    PageVehicleDatabase: typeof import('./components/pages/pageVehicleDatabase.vue')['default']
    PageVehicleInfo: typeof import('./components/pages/pageVehicleInfo.vue')['default']
    PageWeaponInfo: typeof import('./components/pages/pageWeaponInfo.vue')['default']
    PageWeaponsDatabase: typeof import('./components/pages/pageWeaponsDatabase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
